#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Mon Oct 15 14:02:14 2012

import wx
import del_python_ext

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_2 = wx.Panel(self, -1)
        self.label_2 = wx.StaticText(self.panel_2, -1, "                 File to store latent states")
        self.text_ctrl_1 = wx.TextCtrl(self.panel_2, -1, "")
        self.panel_3 = wx.Panel(self, -1)
        self.label_3 = wx.StaticText(self.panel_3, -1, "                 File to store observations")
        self.text_ctrl_2 = wx.TextCtrl(self.panel_3, -1, "")
        self.panel_1 = wx.Panel(self, -1)
        self.label_1 = wx.StaticText(self.panel_1, -1, "   Set\n model")
        self.choice_1 = wx.Choice(self.panel_1, -1, choices=["Bearingonly", "SV model"])
        self.panel_4 = wx.Panel(self, -1)
        self.label_4 = wx.StaticText(self.panel_4, -1, "      Input\ntime length")
        self.text_ctrl_3 = wx.TextCtrl(self.panel_4, -1, "")
        self.label_5 = wx.StaticText(self.panel_4, -1, "     Input\ntime step")
        self.text_ctrl_4 = wx.TextCtrl(self.panel_4, -1, "")
        self.button_1 = wx.Button(self, -1, "generate")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.generateData, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("del simulated data generator")
        self.choice_1.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_6.Add(self.label_2, 0, wx.EXPAND, 3)
        sizer_6.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)
        self.panel_2.SetSizer(sizer_6)
        sizer_2.Add(self.panel_2, 1, wx.EXPAND, 0)
        sizer_7.Add(self.label_3, 0, wx.EXPAND, 0)
        sizer_7.Add(self.text_ctrl_2, 0, wx.EXPAND, 0)
        self.panel_3.SetSizer(sizer_7)
        sizer_2.Add(self.panel_3, 1, wx.EXPAND, 0)
        sizer_5.Add(self.label_1, 0, wx.EXPAND, 0)
        sizer_5.Add(self.choice_1, 0, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_5)
        sizer_4.Add(self.panel_1, 0, wx.EXPAND, 0)
        sizer_8.Add(self.label_4, 0, 0, 0)
        sizer_8.Add(self.text_ctrl_3, 0, wx.EXPAND, 0)
        sizer_8.Add(self.label_5, 0, wx.EXPAND, 0)
        sizer_8.Add(self.text_ctrl_4, 0, wx.EXPAND, 0)
        self.panel_4.SetSizer(sizer_8)
        sizer_4.Add(self.panel_4, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 0, wx.EXPAND, 1)
        sizer_3.Add(self.button_1, 0, wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def generateData(self, event):  # wxGlade: MyFrame.<event_handler>
        model = self.choice_1.GetStringSelection()
        model_index = self.choice_1.GetSelection()
        time = float(self.text_ctrl_3.GetValue())
        step = float(self.text_ctrl_4.GetValue())
        state_file = str(self.text_ctrl_1.GetValue())
        observe_file = str(self.text_ctrl_2.GetValue())
        del_python_ext.generateData(model_index, time, step, state_file, observe_file)

# end of class MyFrame
if __name__ == "__main__":
    del_generator = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    del_generator.SetTopWindow(frame_1)
    frame_1.Show()
    del_generator.MainLoop()
